config/routes.rb
Albm::Application.routes.draw do
  resources :albums do
  resources :photos
 end

  get "home/index"

   root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
validates :name, :presence => true, :uniqueness => true
validates :description, :presence => true, :length => {:minimum => 5}
 #paperclip
  has_attached_file :image,
     :styles => {
       :thumb=> "100x100#",
       :small  => "200x200>" }

has_many :photos, :dependent => :destroy
  has_many :tags
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

end

app/models/photo.rb
class Photo < ActiveRecord::Base


  belongs_to :album

#paperclip
  has_attached_file :image_url,
     :styles => {
       :thumb=> "100x100#",
       :small  => "200x200>" },
	:presence => true


validates :image_url, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to(@album, :notice => 'Album was successfully created.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
def create
  @album = Album.find(params[:album_id])
  @photo = @album.photos.create(params[:photo])
  redirect_to album_path(@album)
end

def destroy
  @album = Album.find(params[:album_id])
  @photo = @album.photos.find(params[:id])
  @photo.destroy
  redirect_to album_path(@album)
end



end

app/helpers/albums_helper.rb
module AlbumsHelper

def join_tags(album)
  album.tags.map { |t| t.name }.join(", ")
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<% @album.tags.build %>
<%= form_for @album  , :html => { :multipart => true } do |album_form| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= album_form.label :name %><br />
    <%= album_form.text_field :name %>
  </div>
  <div class="field">
    <%= album_form.label :description %><br />
    <%= album_form.text_area :description %>
  </div>
  <div class="field">
    <%= album_form.label :image_url %><br />
	<%= album_form.file_field :image %>
  </div>
<h2>Tags</h2>
<%= render :partial => 'tags/form',
           :locals => {:form => album_form} %>

  <div class="actions">
    <%= album_form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Your Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Your Albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= (album.name).capitalize %></td>
<div class="field" , height= 500px ,  width =200px >     
<td><%= album.description %></td>
</div>
<div class ="image" ,height = 500px , width = 300px >   
 <td><% if album.image.exists? then %>
	<%= image_tag album.image.url(:small) %>
<% end %> </td>
</div>

    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>Create New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3><b>Album Name:
  <%= (@album.name).capitalize %></b></h3>
</p>



<p>
 <% if @album.image.exists? then %>
	<%= image_tag @album.image.url(:small) %>
<% end %> 
 
</p>
<p>
  <b>Tags:</b>
  <%= join_tags(@album) %>

</p>
<%= link_to 'Add or Remove Tags', edit_album_path(@album) %>

<h2>Your Album</h2>
<table>
<% @album.photos.each do |photo| %>

<td>
  <div class="image", height =500px , width =200px >  
  <p>
     <% if photo.image_url.exists? then %>
	<%= image_tag photo.image_url.url(:small) %>
<% end %>

  </p>
<p>
  <%= link_to 'Destroy Photo', [photo.album, photo],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>
</div>
</td>


<% end %>
</table>

<h2>Add photos to your album:</h2>
<%= render "photos/form" %>



<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/home/index.html.erb
<h1><b>Welcome to my application. This application will help you in creating a photo album.</b></h1>
<%= link_to "Create your album" , albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Albm</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for([@album, @album.photos.build] , :html => { :multipart => true }) do |f| %>
  <div class="field">
     
     <%= f.file_field :image_url %>
  </div>
  <div class="actions">
     <%= f.submit %>
  </div>
<% end %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
     <%= tag_form.label :name, 'Tag:' %>
     <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
     <div class="field">
       <%= tag_form.label :_destroy, 'Remove:' %>
       <%= tag_form.check_box :_destroy %>
     </div>
  <% end %>
<% end %>